### ISSUE TITLE
KeyError: 'classification_head_1/spatial_reduction_1/reduction_type'

### ISSUE THREAD

**Issue by chyt** [keras-team/autokeras#1183] opened 2020-06-09 03:05 UTC
AutoKeras version: master
KerasTuner version: master
TensorFlow version: 2.2.0

I am running a multi label image classifier based on the example code here: https://autokeras.com/tutorial/image_classification/

I was able to get the example code working with these dependency versions.

Now I am trying to modify the code to run on my own dataset. I have loaded in my own images and labels. I have set `multi_label=True` since my dataset can have more than one label per image.

My process seems to be pretty standard. After loading in the data and labels, I transform them into numpy arrays, then use `MultiLabelBinarizer` to pre-process, split into test and train sets, and run the image classiifer. Code is here:

```
data = np.array(data, dtype="float") / 255.0
labels = np.array(labels)

# binarize the labels using scikit-learn's special multi-label
# binarizer implementation
print("[INFO] class labels:")
mlb = MultiLabelBinarizer()
labels = mlb.fit_transform(labels)
# loop over each of the possible class labels and show them
for (i, label) in enumerate(mlb.classes_):
    print("{}. {}".format(i + 1, label))

(x_train, x_test, y_train, y_test) = train_test_split(data, labels, test_size=0.2, random_state=42)
print(x_train.shape)  # (60000, 28, 28)
print(y_train.shape)  # (60000,)
print(y_train[:3])  # array([7, 2, 1], dtype=uint8)
```

Afterwards, code is straight from the example, except setting `multi_label=True`:

```
# Initialize the image classifier.
clf = ak.ImageClassifier(max_trials=3, multi_label=True)  # It tries 10 different models.
# Feed the image classifier with training data.
clf.fit(x_train, y_train, epochs=3)


# Predict with the best model.
predicted_y = clf.predict(x_test)
print(predicted_y)


# Evaluate the best model with testing data.
print(clf.evaluate(x_test, y_test))
```

The code runs fine for a few trials. Then, I get this error:

```
KeyError: 'classification_head_1/spatial_reduction_1/reduction_type'
[Warning] Invalid model 0/5
```

Here is the full stack trace:

```
Starting new trial
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 105, in build
    model = self.hypermodel.build(hp)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 65, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/graph.py", line 235, in build
    outputs = block.build(hp, inputs=temp_inputs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/engine/block.py", line 34, in _build_wrapper
    return super()._build_wrapper(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 65, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/blocks/heads.py", line 82, in build
    output_node = reduction.SpatialReduction().build(hp, output_node)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/engine/block.py", line 34, in _build_wrapper
    return super()._build_wrapper(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 65, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/blocks/reduction.py", line 106, in build
    default='global_avg')
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hyperparameters.py", line 691, in Choice
    return self._retrieve(hp)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hyperparameters.py", line 619, in _retrieve
    return self.values[hp.name]
KeyError: 'classification_head_1/spatial_reduction_1/reduction_type'
[Warning] Invalid model 0/5
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 105, in build
    model = self.hypermodel.build(hp)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 65, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/graph.py", line 235, in build
    outputs = block.build(hp, inputs=temp_inputs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/engine/block.py", line 34, in _build_wrapper
    return super()._build_wrapper(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 65, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/blocks/heads.py", line 82, in build
    output_node = reduction.SpatialReduction().build(hp, output_node)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/engine/block.py", line 34, in _build_wrapper
    return super()._build_wrapper(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 65, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/blocks/reduction.py", line 106, in build
    default='global_avg')
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hyperparameters.py", line 691, in Choice
    return self._retrieve(hp)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hyperparameters.py", line 619, in _retrieve
    return self.values[hp.name]
KeyError: 'classification_head_1/spatial_reduction_1/reduction_type'
[Warning] Invalid model 1/5
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 105, in build
    model = self.hypermodel.build(hp)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 65, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/graph.py", line 235, in build
    outputs = block.build(hp, inputs=temp_inputs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/engine/block.py", line 34, in _build_wrapper
    return super()._build_wrapper(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 65, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/blocks/heads.py", line 82, in build
    output_node = reduction.SpatialReduction().build(hp, output_node)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/engine/block.py", line 34, in _build_wrapper
    return super()._build_wrapper(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 65, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/blocks/reduction.py", line 106, in build
    default='global_avg')
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hyperparameters.py", line 691, in Choice
    return self._retrieve(hp)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hyperparameters.py", line 619, in _retrieve
    return self.values[hp.name]
KeyError: 'classification_head_1/spatial_reduction_1/reduction_type'
[Warning] Invalid model 2/5
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 105, in build
    model = self.hypermodel.build(hp)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 65, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/graph.py", line 235, in build
    outputs = block.build(hp, inputs=temp_inputs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/engine/block.py", line 34, in _build_wrapper
    return super()._build_wrapper(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 65, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/blocks/heads.py", line 82, in build
    output_node = reduction.SpatialReduction().build(hp, output_node)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/engine/block.py", line 34, in _build_wrapper
    return super()._build_wrapper(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 65, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/blocks/reduction.py", line 106, in build
    default='global_avg')
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hyperparameters.py", line 691, in Choice
    return self._retrieve(hp)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hyperparameters.py", line 619, in _retrieve
    return self.values[hp.name]
KeyError: 'classification_head_1/spatial_reduction_1/reduction_type'
[Warning] Invalid model 3/5
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 105, in build
    model = self.hypermodel.build(hp)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 65, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/graph.py", line 235, in build
    outputs = block.build(hp, inputs=temp_inputs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/engine/block.py", line 34, in _build_wrapper
    return super()._build_wrapper(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 65, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/blocks/heads.py", line 82, in build
    output_node = reduction.SpatialReduction().build(hp, output_node)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/engine/block.py", line 34, in _build_wrapper
    return super()._build_wrapper(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 65, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/blocks/reduction.py", line 106, in build
    default='global_avg')
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hyperparameters.py", line 691, in Choice
    return self._retrieve(hp)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hyperparameters.py", line 619, in _retrieve
    return self.values[hp.name]
KeyError: 'classification_head_1/spatial_reduction_1/reduction_type'
[Warning] Invalid model 4/5
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 105, in build
    model = self.hypermodel.build(hp)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 65, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/graph.py", line 235, in build
    outputs = block.build(hp, inputs=temp_inputs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/engine/block.py", line 34, in _build_wrapper
    return super()._build_wrapper(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 65, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/blocks/heads.py", line 82, in build
    output_node = reduction.SpatialReduction().build(hp, output_node)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/engine/block.py", line 34, in _build_wrapper
    return super()._build_wrapper(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 65, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/blocks/reduction.py", line 106, in build
    default='global_avg')
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hyperparameters.py", line 691, in Choice
    return self._retrieve(hp)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hyperparameters.py", line 619, in _retrieve
    return self.values[hp.name]
KeyError: 'classification_head_1/spatial_reduction_1/reduction_type'
[Warning] Invalid model 5/5
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py in build(self, hp)
    104                 with maybe_distribute(self.distribution_strategy):
--> 105                     model = self.hypermodel.build(hp)
    106             except:

17 frames
KeyError: 'classification_head_1/spatial_reduction_1/reduction_type'

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py in build(self, hp)
    113                 if i == self._max_fail_streak:
    114                     raise RuntimeError(
--> 115                         'Too many failed attempts to build model.')
    116                 continue
    117 

RuntimeError: Too many failed attempts to build model.
```

How can I resolve this?

**Comment by haifeng-jin** [comment] 2020-06-25 00:28
Thank you for the report! I think it is fixed in the latest release 1.0.3. If it doesn't, please let me know. Thanks.

**Comment by anthayes92** [comment] 2020-06-30 11:48
I consitently experienced the exact same KeyError: 'classification_head_1/spatial_reduction_1/reduction_type' which then caused the RuntimeError: Too many failed attempts to build model. 
**Solved** by upgrading keras-base to 2.4.3

**Comment by castrovictor** [comment] 2020-07-02 16:57
I'm having the same issue, but with Image Classifier. My autokeras version is 1.0.3

**Comment by I-Kryachko** [comment] 2020-07-07 21:21
I have the same issue with Image Classifier. Also version is 1.0.3. My dataset is like:
```
tdataset = tf.data.Dataset.from_tensor_slices((tfilenames, tannotations))
vdataset = tf.data.Dataset.from_tensor_slices((vfilenames, vannotations))
...
tdataset = tdataset.map(BasicPreprocessor(im_size, 0))
vdataset = vdataset.map(BasicPreprocessor(im_size, 1))
```

Preprocessor is:
```
    @tf.function
    def preprocess_annotated(self, data, annotation):
        if self.pipeline == 0 or self.pipeline == 1:
            image_string = tf.io.read_file(data)
            image = tf.image.decode_image(image_string, channels=3)
            image.set_shape(shape=[None, None, 3])
            images = self.adjust_pixelwise(image)
        else:
            images = data

        images = self.resize_to(image=images, sz=self.images_size, keep_scales=self.keep_scales)

        return images, annotation
```
where `self.resize_to` is call of `tf.image.resize(images=image, size=(sz, sz))`; `self.adjust_pixelwise` is:
```
result = tf.divide(image, tf.constant(2.0))
result = tf.add(result, tf.constant(0.5))
result = tf.image.convert_image_dtype(result, tf.uint8)
return result
```
The other code is from Get Started example.
Sometimes it works well but when trials reach something with 'classification_head_1/spatial_reduction_1/reduction_type' I get the error mentioned earlier. Once i hade nearly 60 trials finished without this error and I think there was no `spatial_reduction_1` block inside any trial. And most of the times I have only nearly 3-7 trials working correctly and then an error appears.

Any workarounds?

**Comment by haifeng-jin** [comment] 2020-07-12 02:16
I might because of the `overwrite=False`. Just change it to True may solve the problem.

**Comment by I-Kryachko** [comment] 2020-07-12 08:21
@haifeng-jin 
For me issue happens when I start training without interrupting and resuming the process, wothout any previously saved checkpoints. That is why the result is the same with `overwrite=False` or with `overwrite=True`.

**Comment by castrovictor** [comment] 2020-07-14 19:24
> I might because of the `overwrite=False`. Just change it to True may solve the problem.

I'll try with this, if it does not solve the issue, I will notify.

As @I-Kryachko , my issue is starting training from scratch.

And finally, I have to say that the error didn't show up in the last 3-4 trials I made, but I got a run out of memory error. So not sure what's going on with the previous issue.

**Comment by castrovictor** [comment] 2020-07-15 15:01
Update: I can't even finish a trial, I get an error of running out of memory which disappears if I do not use `overwrite=False`

**Comment by haifeng-jin** [comment] 2020-07-15 20:36
Thanks everyone!
As I talked to chyt, we don't see this error any more with ak 1.0.3 and kt 1.0.2rc0.
Not sure how to reproduce it. I am running totally fine locally.

**Comment by I-Kryachko** [comment] 2020-07-15 20:42
Sometimes I run ok too. It happens for me at ak 1.0.3 when tuner decides to make certain improvents on get started task. Two tasks which I run one by one do not run the same layers, so sometimes I have error.

**Closed** 2020-07-17 20:52 UTC

**Comment by dahlo** [comment] 2020-07-18 22:14
Can confirm working. Running ~30 instances i would get about 1 crash per hour with the KeyError. I have now run over 24h and not a single crash. Running autokeras 7db2afd and keras-tuner fa84eb2.

**Comment by castrovictor** [comment] 2020-07-19 16:10
@dahlo would you mind posting your configuration? Installing the versions you mention I get this error:


ImportError: dlopen: cannot load any more object with static TLS
___________________________________________________________________________
Contents of /mnt/sdd/vicastro/envs/ak4/lib/python3.8/site-packages/sklearn/__check_build:
__pycache__               setup.py                  _check_build.cpython-38-x86_64-linux-gnu.so
__init__.py
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

**Comment by dahlo** [comment] 2020-07-19 21:13
@castrovictor Sure thing. I'm running using the following Dockerfile:

`FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04

# install apt packages
RUN apt update && apt upgrade -y && apt install -y \
        curl \
        git \
        python3 \
        python3-pip \
        vim \
        wget

# install pip packages
RUN pip3 install --no-cache-dir -U pip
RUN pip3 install --no-cache-dir -U setuptools six
RUN pip3 install --no-cache-dir \
        scipy==1.4.1 \
        tensorflow-gpu==2.2.0 \
        git+https://github.com/keras-team/autokeras.git@7db2afd \
        git+https://github.com/keras-team/keras-tuner.git@fa84eb2

# clean the cache
RUN rm -rf /var/lib/apt/lists/* && rm -rf ~/.cache/pip/*`

Running pip3 freeze inside the container gives the following:

`$ pip3 freeze 
absl-py==0.9.0
asn1crypto==0.24.0
astunparse==1.6.3
autokeras @ git+https://github.com/keras-team/autokeras.git@7db2afde4af83ca113841a979e218d775a04eb40
backcall==0.2.0
cachetools==4.1.1
certifi==2020.6.20
chardet==3.0.4
colorama==0.4.3
cryptography==2.1.4
decorator==4.4.2
future==0.18.2
gast==0.3.3
google-auth==1.19.2
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.30.0
h5py==2.10.0
idna==2.6
importlib-metadata==1.7.0
ipython==7.16.1
ipython-genutils==0.2.0
jedi==0.17.2
joblib==0.16.0
Keras-Preprocessing==1.1.2
keras-tuner @ git+https://github.com/keras-team/keras-tuner.git@fa84eb29446f6234aea243a73cef85de4bbdb642
keyring==10.6.0
keyrings.alt==3.0
Markdown==3.2.2
numpy==1.19.0
oauthlib==3.1.0
opt-einsum==3.2.1
packaging==20.4
pandas==1.0.5
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
prompt-toolkit==3.0.5
protobuf==3.12.2
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycrypto==2.6.1
Pygments==2.6.1
pygobject==3.26.1
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.1
pyxdg==0.25
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
scikit-learn==0.23.1
scipy==1.4.1
SecretStorage==2.3.1
six==1.15.0
tabulate==0.8.7
tensorboard==2.2.2
tensorboard-plugin-wit==1.7.0
tensorflow==2.2.0
tensorflow-estimator==2.2.0
tensorflow-gpu==2.2.0
termcolor==1.1.0
terminaltables==3.1.0
threadpoolctl==2.1.0
tqdm==4.48.0
traitlets==4.3.3
urllib3==1.25.9
wcwidth==0.2.5
Werkzeug==1.0.1
wrapt==1.12.1
zipp==3.1.0`

and python version:

`$ python3 --version
Python 3.6.9`

**Comment by mmortazavi** [comment] 2022-02-04 07:00
I am running into a similar issue with the latest version and `overwrite=True.` 
Autokeras: 1.0.17
Python: 3.9.10 

Here is the full stack trace:

```
Trial 3 Complete [10h 14m 30s]
val_loss: 0.29048436880111694

Best val_loss So Far: 0.29048436880111694
Total elapsed time: 12h 58m 04s
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [7], in <module>
      1 tensorboard_callback = tf.keras.callbacks.TensorBoard(logdir, histogram_freq=1)
      3 model = ak.ImageClassifier(overwrite=True, max_trials=30)
----> 4 history = model.fit(train_data, epochs=10, callbacks=[tensorboard_callback])

File ~/Git/ipig/venv/lib/python3.9/site-packages/autokeras/tasks/image.py:164, in ImageClassifier.fit(self, x, y, epochs, callbacks, validation_split, validation_data, **kwargs)
    107 def fit(
    108     self,
    109     x: Optional[types.DatasetType] = None,
   (...)
    117     **kwargs
    118 ):
    119     """Search for the best model and hyperparameters for the AutoModel.
    120 
    121     It will search for the best model based on the performances on
   (...)
    162             validation loss values and validation metrics values (if applicable).
    163     """
--> 164     history = super().fit(
    165         x=x,
    166         y=y,
    167         epochs=epochs,
    168         callbacks=callbacks,
    169         validation_split=validation_split,
    170         validation_data=validation_data,
    171         **kwargs
    172     )
    173     return history

File ~/Git/ipig/venv/lib/python3.9/site-packages/autokeras/auto_model.py:288, in AutoModel.fit(self, x, y, batch_size, epochs, callbacks, validation_split, validation_data, verbose, **kwargs)
    283 if validation_data is None and validation_split:
    284     dataset, validation_data = data_utils.split_dataset(
    285         dataset, validation_split
    286     )
--> 288 history = self.tuner.search(
    289     x=dataset,
    290     epochs=epochs,
    291     callbacks=callbacks,
    292     validation_data=validation_data,
    293     validation_split=validation_split,
    294     verbose=verbose,
    295     **kwargs
    296 )
    298 return history

File ~/Git/ipig/venv/lib/python3.9/site-packages/autokeras/engine/tuner.py:193, in AutoTuner.search(self, epochs, callbacks, validation_split, verbose, **fit_kwargs)
    191 self.hypermodel.build(hp)
    192 self.oracle.update_space(hp)
--> 193 super().search(
    194     epochs=epochs, callbacks=new_callbacks, verbose=verbose, **fit_kwargs
    195 )
    197 # Train the best model use validation data.
    198 # Train the best model with enough number of epochs.
    199 if validation_split > 0 or early_stopping_inserted:

File ~/Git/ipig/venv/lib/python3.9/site-packages/keras_tuner/engine/base_tuner.py:169, in BaseTuner.search(self, *fit_args, **fit_kwargs)
    167 self.on_search_begin()
    168 while True:
--> 169     trial = self.oracle.create_trial(self.tuner_id)
    170     if trial.status == trial_module.TrialStatus.STOPPED:
    171         # Oracle triggered exit.
    172         tf.get_logger().info("Oracle triggered exit")

File ~/Git/ipig/venv/lib/python3.9/site-packages/keras_tuner/engine/oracle.py:189, in Oracle.create_trial(self, tuner_id)
    187     values = None
    188 else:
--> 189     response = self.populate_space(trial_id)
    190     status = response["status"]
    191     values = response["values"] if "values" in response else None

File ~/Git/ipig/venv/lib/python3.9/site-packages/autokeras/tuners/greedy.py:153, in GreedyOracle.populate_space(self, trial_id)
    151 for _ in range(self._max_collisions):
    152     hp_names = self._select_hps()
--> 153     values = self._generate_hp_values(hp_names)
    154     # Reached max collisions.
    155     if values is None:

File ~/Git/ipig/venv/lib/python3.9/site-packages/autokeras/tuners/greedy.py:189, in GreedyOracle._generate_hp_values(self, hp_names)
    186 if hps.is_active(hp):
    187     # if was active and not selected, do nothing.
    188     if best_hps.is_active(hp.name) and hp.name not in hp_names:
--> 189         hps.values[hp.name] = best_hps.values[hp.name]
    190         continue
    191     # if was not active or selected, sample.

KeyError: 'classification_head_1/spatial_reduction_2/reduction_type'
```
