### ISSUE TITLE
Support for finding Training models for Object Detecton 

### ISSUE THREAD

**Issue by takeofuture** [keras-team/autokeras#1236] opened 2020-07-16 00:47 UTC
I see another issue thread which has been already closed.

So objectDetection models eventually supported, (I am not talking about pretrained model, I assume it is not the job for autokeras as AutoML as it main objective is to automatically search and find candidates for the models based on given data).
I am assuming given training dat asimilar like COCO or so (class label + (x, y, h, w) ) * xxx, then it find the good model for object detection automatically. Any update so far? I am looking forward to using it!

**Comment by haifeng-jin** [comment] 2020-07-28 07:13
duplicate of #925

**Closed by haifeng-jin** 2020-07-28 07:13 UTC
Labels: feature request
