### ISSUE TITLE
use my own generator,the autokeras always reading data,not start work.

### ISSUE THREAD

**Issue by jackyesf** [keras-team/autokeras#1343] opened 2020-09-18 09:58 UTC
import autokeras as ak

train_set = tf.data.Dataset.from_generator(get_data_from_directory,(tf.float32,tf.float32), (tf.TensorShape([10,1205,6,1]), tf.TensorShape([10,])))
train_set = train_set.batch(15)
train_set = train_set.repeat(1)

clf = ak.ImageClassifier(
    overwrite=True,
    max_trials=3)
# Feed the tensorflow Dataset to the classifier.
clf.fit(train_set,validation_split=0.2, epochs=2)

# Export as a Keras Model.
model = clf.export_model()
print(type(model))  
model.summary()
model.save("model_autokeras.h5")

**Comment by haifeng-jin** [comment] 2020-10-02 15:13
We are working on to support this feature.
It is a duplicate of 
#984

**Closed** 2020-12-09 08:43 UTC
Labels: wontfix
